name: Build App (New)

on: workflow_dispatch

jobs:
  build:
    name: Run build
    runs-on: macos-latest # Required for macOS signing

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        cache: 'npm'
    - name: Install Node.js dependencies
      run: npm install
    - name: Build app
      run: npx electron-builder build -mlw --x64 --arm64
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: all-artiffacts
        path: dist