name: Build App (New)

on: workflow_dispatch

jobs:
  build:

    strategy:
      matrix:
        arch: ["x64", "arm64"]
        host:
          - {os: macos-latest, displayName: "macOS", artifactPath: "dist/6328 Log Viewer-*.dmg"}
          - {os: ubuntu-latest, displayName: "Linux", artifactPath: "dist/6328-log-viewer_*.deb\ndist/6328-log-viewer_*.rpm"}
          - {os: windows-latest, displayName: "Windows", artifactPath: "dist/6328 Log Viewer Setup *.exe"}

    name: Build for ${{ matrix.host.displayName }} (${{ matrix.arch }})
    runs-on: ${{ matrix.host.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        cache: 'npm'
    - name: Install Node.js dependencies
      run: npm install
    - name: Prepare macOS certificate
      if: ${{ matrix.host.os }} == "macos-latest"
      run: |
        echo "CSC_LINK=${{ secrets.MACOS_CERTIFICATE }}" >> $GITHUB_ENV
        echo "CSC_KEY_PASSWORD=${{ secrets.MACOS_CERTIFICATE_PWD }}" >> $GITHUB_ENV
    - name: Build app
      run: npx electron-builder build --${{ matrix.arch }} --publish never
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.host.displayName }}-${{ matrix.arch }}
        path: ${{ matrix.host.artifactPath }}