name: Build App (New)

on: workflow_dispatch

jobs:
  build:

    strategy:
      matrix:
        arch: ["x64", "arm64"]
        host:
          - {os: macos-latest, displayName: "macOS", artifactPath: "dist/6328 Log Viewer-*.dmg"}
          - {os: ubuntu-latest, displayName: "Linux", artifactPath: "dist/6328-log-viewer_*.deb\ndist/6328-log-viewer_*.rpm"}
          - {os: windows-latest, displayName: "Windows", artifactPath: "dist/6328 Log Viewer Setup *.exe"}

    name: Build for ${{ matrix.host.displayName }} (${{ matrix.arch }})
    runs-on: ${{ matrix.host.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        cache: 'npm'
    - name: Install Node.js dependencies
      run: npm install
    - name: Build app
      run: npx electron-builder build --${{ matrix.arch }} --publish never
      env:
        CSC_LINK: "${{ matrix.host.os == 'macos-latest' && secrets.MACOS_CERTIFICATE || '' }}"
        CSC_KEY_PASSWORD: "${{ matrix.host.os == 'macos-latest' && secrets.MACOS_CERTIFICATE_PWD || '' }}"
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.host.displayName }}-${{ matrix.arch }}
        path: ${{ matrix.host.artifactPath }}